// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/server/internal/repository/ent/achievement"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AchievementCreate is the builder for creating a Achievement entity.
type AchievementCreate struct {
	config
	mutation *AchievementMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AchievementCreate) SetCreatedAt(v int64) *AchievementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AchievementCreate) SetNillableCreatedAt(v *int64) *AchievementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AchievementCreate) SetUpdatedAt(v int64) *AchievementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AchievementCreate) SetNillableUpdatedAt(v *int64) *AchievementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AchievementCreate) SetName(v string) *AchievementCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AchievementCreate) SetDescription(v string) *AchievementCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *AchievementCreate) SetIcon(v string) *AchievementCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetConditionType sets the "condition_type" field.
func (_c *AchievementCreate) SetConditionType(v string) *AchievementCreate {
	_c.mutation.SetConditionType(v)
	return _c
}

// SetConditionValue sets the "condition_value" field.
func (_c *AchievementCreate) SetConditionValue(v int) *AchievementCreate {
	_c.mutation.SetConditionValue(v)
	return _c
}

// SetNillableConditionValue sets the "condition_value" field if the given value is not nil.
func (_c *AchievementCreate) SetNillableConditionValue(v *int) *AchievementCreate {
	if v != nil {
		_c.SetConditionValue(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AchievementCreate) SetID(v string) *AchievementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AchievementCreate) SetNillableID(v *string) *AchievementCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AchievementMutation object of the builder.
func (_c *AchievementCreate) Mutation() *AchievementMutation {
	return _c.mutation
}

// Save creates the Achievement in the database.
func (_c *AchievementCreate) Save(ctx context.Context) (*Achievement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AchievementCreate) SaveX(ctx context.Context) *Achievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AchievementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AchievementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AchievementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := achievement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := achievement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ConditionValue(); !ok {
		v := achievement.DefaultConditionValue
		_c.mutation.SetConditionValue(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := achievement.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AchievementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Achievement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Achievement.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Achievement.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := achievement.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Achievement.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Achievement.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := achievement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Achievement.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Achievement.icon"`)}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := achievement.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "Achievement.icon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConditionType(); !ok {
		return &ValidationError{Name: "condition_type", err: errors.New(`ent: missing required field "Achievement.condition_type"`)}
	}
	if v, ok := _c.mutation.ConditionType(); ok {
		if err := achievement.ConditionTypeValidator(v); err != nil {
			return &ValidationError{Name: "condition_type", err: fmt.Errorf(`ent: validator failed for field "Achievement.condition_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConditionValue(); !ok {
		return &ValidationError{Name: "condition_value", err: errors.New(`ent: missing required field "Achievement.condition_value"`)}
	}
	return nil
}

func (_c *AchievementCreate) sqlSave(ctx context.Context) (*Achievement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Achievement.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AchievementCreate) createSpec() (*Achievement, *sqlgraph.CreateSpec) {
	var (
		_node = &Achievement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(achievement.Table, sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(achievement.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(achievement.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(achievement.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(achievement.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(achievement.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.ConditionType(); ok {
		_spec.SetField(achievement.FieldConditionType, field.TypeString, value)
		_node.ConditionType = value
	}
	if value, ok := _c.mutation.ConditionValue(); ok {
		_spec.SetField(achievement.FieldConditionValue, field.TypeInt, value)
		_node.ConditionValue = value
	}
	return _node, _spec
}

// AchievementCreateBulk is the builder for creating many Achievement entities in bulk.
type AchievementCreateBulk struct {
	config
	err      error
	builders []*AchievementCreate
}

// Save creates the Achievement entities in the database.
func (_c *AchievementCreateBulk) Save(ctx context.Context) ([]*Achievement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Achievement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AchievementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AchievementCreateBulk) SaveX(ctx context.Context) []*Achievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AchievementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AchievementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
