// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/server/internal/repository/ent/article"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleCreate is the builder for creating a Article entity.
type ArticleCreate struct {
	config
	mutation *ArticleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArticleCreate) SetCreatedAt(v int64) *ArticleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableCreatedAt(v *int64) *ArticleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArticleCreate) SetUpdatedAt(v int64) *ArticleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableUpdatedAt(v *int64) *ArticleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ArticleCreate) SetTitle(v string) *ArticleCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ArticleCreate) SetSummary(v string) *ArticleCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableSummary(v *string) *ArticleCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ArticleCreate) SetContent(v string) *ArticleCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableContent(v *string) *ArticleCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *ArticleCreate) SetCategoryID(v string) *ArticleCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetAuthor sets the "author" field.
func (_c *ArticleCreate) SetAuthor(v string) *ArticleCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *ArticleCreate) SetPublishedAt(v int64) *ArticleCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetReadTime sets the "read_time" field.
func (_c *ArticleCreate) SetReadTime(v int) *ArticleCreate {
	_c.mutation.SetReadTime(v)
	return _c
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableReadTime(v *int) *ArticleCreate {
	if v != nil {
		_c.SetReadTime(*v)
	}
	return _c
}

// SetXpReward sets the "xp_reward" field.
func (_c *ArticleCreate) SetXpReward(v int) *ArticleCreate {
	_c.mutation.SetXpReward(v)
	return _c
}

// SetNillableXpReward sets the "xp_reward" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableXpReward(v *int) *ArticleCreate {
	if v != nil {
		_c.SetXpReward(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *ArticleCreate) SetImageURL(v string) *ArticleCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableImageURL(v *string) *ArticleCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ArticleCreate) SetTags(v []string) *ArticleCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetIsFeatured sets the "is_featured" field.
func (_c *ArticleCreate) SetIsFeatured(v bool) *ArticleCreate {
	_c.mutation.SetIsFeatured(v)
	return _c
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableIsFeatured(v *bool) *ArticleCreate {
	if v != nil {
		_c.SetIsFeatured(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ArticleCreate) SetSourceID(v string) *ArticleCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableSourceID(v *string) *ArticleCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *ArticleCreate) SetSourceURL(v string) *ArticleCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetSourceName sets the "source_name" field.
func (_c *ArticleCreate) SetSourceName(v string) *ArticleCreate {
	_c.mutation.SetSourceName(v)
	return _c
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableSourceName(v *string) *ArticleCreate {
	if v != nil {
		_c.SetSourceName(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *ArticleCreate) SetViewCount(v int) *ArticleCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableViewCount(v *int) *ArticleCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetCommentCount sets the "comment_count" field.
func (_c *ArticleCreate) SetCommentCount(v int) *ArticleCreate {
	_c.mutation.SetCommentCount(v)
	return _c
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableCommentCount(v *int) *ArticleCreate {
	if v != nil {
		_c.SetCommentCount(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *ArticleCreate) SetLikeCount(v int) *ArticleCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableLikeCount(v *int) *ArticleCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetCollectedAt sets the "collected_at" field.
func (_c *ArticleCreate) SetCollectedAt(v int64) *ArticleCreate {
	_c.mutation.SetCollectedAt(v)
	return _c
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableCollectedAt(v *int64) *ArticleCreate {
	if v != nil {
		_c.SetCollectedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ArticleCreate) SetID(v string) *ArticleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableID(v *string) *ArticleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ArticleMutation object of the builder.
func (_c *ArticleCreate) Mutation() *ArticleMutation {
	return _c.mutation
}

// Save creates the Article in the database.
func (_c *ArticleCreate) Save(ctx context.Context) (*Article, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArticleCreate) SaveX(ctx context.Context) *Article {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArticleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := article.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := article.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ReadTime(); !ok {
		v := article.DefaultReadTime
		_c.mutation.SetReadTime(v)
	}
	if _, ok := _c.mutation.XpReward(); !ok {
		v := article.DefaultXpReward
		_c.mutation.SetXpReward(v)
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		v := article.DefaultIsFeatured
		_c.mutation.SetIsFeatured(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := article.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		v := article.DefaultCommentCount
		_c.mutation.SetCommentCount(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := article.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.CollectedAt(); !ok {
		v := article.DefaultCollectedAt()
		_c.mutation.SetCollectedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := article.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArticleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Article.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Article.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Article.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "Article.category_id"`)}
	}
	if v, ok := _c.mutation.CategoryID(); ok {
		if err := article.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Article.category_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Article.author"`)}
	}
	if v, ok := _c.mutation.Author(); ok {
		if err := article.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Article.author": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublishedAt(); !ok {
		return &ValidationError{Name: "published_at", err: errors.New(`ent: missing required field "Article.published_at"`)}
	}
	if _, ok := _c.mutation.ReadTime(); !ok {
		return &ValidationError{Name: "read_time", err: errors.New(`ent: missing required field "Article.read_time"`)}
	}
	if _, ok := _c.mutation.XpReward(); !ok {
		return &ValidationError{Name: "xp_reward", err: errors.New(`ent: missing required field "Article.xp_reward"`)}
	}
	if v, ok := _c.mutation.ImageURL(); ok {
		if err := article.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Article.image_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		return &ValidationError{Name: "is_featured", err: errors.New(`ent: missing required field "Article.is_featured"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "Article.source_url"`)}
	}
	if v, ok := _c.mutation.SourceURL(); ok {
		if err := article.SourceURLValidator(v); err != nil {
			return &ValidationError{Name: "source_url", err: fmt.Errorf(`ent: validator failed for field "Article.source_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Article.view_count"`)}
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		return &ValidationError{Name: "comment_count", err: errors.New(`ent: missing required field "Article.comment_count"`)}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "Article.like_count"`)}
	}
	if _, ok := _c.mutation.CollectedAt(); !ok {
		return &ValidationError{Name: "collected_at", err: errors.New(`ent: missing required field "Article.collected_at"`)}
	}
	return nil
}

func (_c *ArticleCreate) sqlSave(ctx context.Context) (*Article, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Article.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArticleCreate) createSpec() (*Article, *sqlgraph.CreateSpec) {
	var (
		_node = &Article{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(article.Table, sqlgraph.NewFieldSpec(article.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(article.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(article.FieldCategoryID, field.TypeString, value)
		_node.CategoryID = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeInt64, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.ReadTime(); ok {
		_spec.SetField(article.FieldReadTime, field.TypeInt, value)
		_node.ReadTime = value
	}
	if value, ok := _c.mutation.XpReward(); ok {
		_spec.SetField(article.FieldXpReward, field.TypeInt, value)
		_node.XpReward = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(article.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.IsFeatured(); ok {
		_spec.SetField(article.FieldIsFeatured, field.TypeBool, value)
		_node.IsFeatured = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(article.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(article.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.SourceName(); ok {
		_spec.SetField(article.FieldSourceName, field.TypeString, value)
		_node.SourceName = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(article.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.CommentCount(); ok {
		_spec.SetField(article.FieldCommentCount, field.TypeInt, value)
		_node.CommentCount = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(article.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.CollectedAt(); ok {
		_spec.SetField(article.FieldCollectedAt, field.TypeInt64, value)
		_node.CollectedAt = value
	}
	return _node, _spec
}

// ArticleCreateBulk is the builder for creating many Article entities in bulk.
type ArticleCreateBulk struct {
	config
	err      error
	builders []*ArticleCreate
}

// Save creates the Article entities in the database.
func (_c *ArticleCreateBulk) Save(ctx context.Context) ([]*Article, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Article, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArticleCreateBulk) SaveX(ctx context.Context) []*Article {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
