// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/server/internal/repository/ent/comment"
	"isolo-news/server/internal/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdate) SetUpdatedAt(v int64) *CommentUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *CommentUpdate) AddUpdatedAt(v int64) *CommentUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *CommentUpdate) SetArticleID(v string) *CommentUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableArticleID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdate) SetUserID(v string) *CommentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableUserID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CommentUpdate) SetParentID(v string) *CommentUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableParentID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CommentUpdate) ClearParentID() *CommentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdate) SetContent(v string) *CommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableContent(v *string) *CommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikes sets the "likes" field.
func (_u *CommentUpdate) SetLikes(v int) *CommentUpdate {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableLikes(v *int) *CommentUpdate {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *CommentUpdate) AddLikes(v int) *CommentUpdate {
	_u.mutation.AddLikes(v)
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdate) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := comment.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "Comment.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := comment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Comment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := comment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Comment.content": %w`, err)}
		}
	}
	return nil
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(comment.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(comment.FieldArticleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(comment.FieldParentID, field.TypeString, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(comment.FieldParentID, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(comment.FieldLikes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(comment.FieldLikes, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdateOne) SetUpdatedAt(v int64) *CommentUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *CommentUpdateOne) AddUpdatedAt(v int64) *CommentUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *CommentUpdateOne) SetArticleID(v string) *CommentUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableArticleID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdateOne) SetUserID(v string) *CommentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableUserID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CommentUpdateOne) SetParentID(v string) *CommentUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableParentID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CommentUpdateOne) ClearParentID() *CommentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdateOne) SetContent(v string) *CommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableContent(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikes sets the "likes" field.
func (_u *CommentUpdateOne) SetLikes(v int) *CommentUpdateOne {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableLikes(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *CommentUpdateOne) AddLikes(v int) *CommentUpdateOne {
	_u.mutation.AddLikes(v)
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdateOne) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := comment.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "Comment.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := comment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Comment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := comment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Comment.content": %w`, err)}
		}
	}
	return nil
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(comment.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(comment.FieldArticleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(comment.FieldParentID, field.TypeString, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(comment.FieldParentID, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(comment.FieldLikes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(comment.FieldLikes, field.TypeInt, value)
	}
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
