// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"isolo-news/server/internal/repository/ent/schedulesetting"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ScheduleSetting is the model entity for the ScheduleSetting schema.
type ScheduleSetting struct {
	config `json:"-"`
	// ID of the ent.
	// ULID 主键
	ID string `json:"id,omitempty"`
	// 创建时间（UTC Unix 时间戳）
	CreatedAt int64 `json:"created_at,omitempty"`
	// 更新时间（UTC Unix 时间戳）
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// 分类 ID
	CategoryID string `json:"category_id,omitempty"`
	// Cron 表达式
	CronExpression string `json:"cron_expression,omitempty"`
	// 是否启用
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduleSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulesetting.FieldIsActive:
			values[i] = new(sql.NullBool)
		case schedulesetting.FieldCreatedAt, schedulesetting.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case schedulesetting.FieldID, schedulesetting.FieldCategoryID, schedulesetting.FieldCronExpression:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduleSetting fields.
func (_m *ScheduleSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulesetting.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case schedulesetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case schedulesetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		case schedulesetting.FieldCategoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = value.String
			}
		case schedulesetting.FieldCronExpression:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_expression", values[i])
			} else if value.Valid {
				_m.CronExpression = value.String
			}
		case schedulesetting.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduleSetting.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduleSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScheduleSetting.
// Note that you need to call ScheduleSetting.Unwrap() before calling this method if this ScheduleSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduleSetting) Update() *ScheduleSettingUpdateOne {
	return NewScheduleSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduleSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduleSetting) Unwrap() *ScheduleSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduleSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduleSetting) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduleSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(_m.CategoryID)
	builder.WriteString(", ")
	builder.WriteString("cron_expression=")
	builder.WriteString(_m.CronExpression)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// ScheduleSettings is a parsable slice of ScheduleSetting.
type ScheduleSettings []*ScheduleSetting
