// Code generated by ent, DO NOT EDIT.

package articleread

import (
	"isolo-news/server/internal/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldUserID, v))
}

// ArticleID applies equality check predicate on the "article_id" field. It's identical to ArticleIDEQ.
func ArticleID(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldArticleID, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldReadAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldContainsFold(FieldUserID, v))
}

// ArticleIDEQ applies the EQ predicate on the "article_id" field.
func ArticleIDEQ(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldArticleID, v))
}

// ArticleIDNEQ applies the NEQ predicate on the "article_id" field.
func ArticleIDNEQ(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldArticleID, v))
}

// ArticleIDIn applies the In predicate on the "article_id" field.
func ArticleIDIn(vs ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldArticleID, vs...))
}

// ArticleIDNotIn applies the NotIn predicate on the "article_id" field.
func ArticleIDNotIn(vs ...string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldArticleID, vs...))
}

// ArticleIDGT applies the GT predicate on the "article_id" field.
func ArticleIDGT(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldArticleID, v))
}

// ArticleIDGTE applies the GTE predicate on the "article_id" field.
func ArticleIDGTE(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldArticleID, v))
}

// ArticleIDLT applies the LT predicate on the "article_id" field.
func ArticleIDLT(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldArticleID, v))
}

// ArticleIDLTE applies the LTE predicate on the "article_id" field.
func ArticleIDLTE(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldArticleID, v))
}

// ArticleIDContains applies the Contains predicate on the "article_id" field.
func ArticleIDContains(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldContains(FieldArticleID, v))
}

// ArticleIDHasPrefix applies the HasPrefix predicate on the "article_id" field.
func ArticleIDHasPrefix(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldHasPrefix(FieldArticleID, v))
}

// ArticleIDHasSuffix applies the HasSuffix predicate on the "article_id" field.
func ArticleIDHasSuffix(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldHasSuffix(FieldArticleID, v))
}

// ArticleIDEqualFold applies the EqualFold predicate on the "article_id" field.
func ArticleIDEqualFold(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEqualFold(FieldArticleID, v))
}

// ArticleIDContainsFold applies the ContainsFold predicate on the "article_id" field.
func ArticleIDContainsFold(v string) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldContainsFold(FieldArticleID, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v int64) predicate.ArticleRead {
	return predicate.ArticleRead(sql.FieldLTE(FieldReadAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ArticleRead) predicate.ArticleRead {
	return predicate.ArticleRead(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ArticleRead) predicate.ArticleRead {
	return predicate.ArticleRead(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ArticleRead) predicate.ArticleRead {
	return predicate.ArticleRead(sql.NotPredicates(p))
}
