// Code generated by ent, DO NOT EDIT.

package user

import (
	"isolo-news/server/internal/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PlayerName applies equality check predicate on the "player_name" field. It's identical to PlayerNameEQ.
func PlayerName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPlayerName, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLevel, v))
}

// Xp applies equality check predicate on the "xp" field. It's identical to XpEQ.
func Xp(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// MaxXp applies equality check predicate on the "max_xp" field. It's identical to MaxXpEQ.
func MaxXp(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxXp, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTitle, v))
}

// ReadArticleCount applies equality check predicate on the "read_article_count" field. It's identical to ReadArticleCountEQ.
func ReadArticleCount(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReadArticleCount, v))
}

// LoginDays applies equality check predicate on the "login_days" field. It's identical to LoginDaysEQ.
func LoginDays(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginDays, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// ThemePreference applies equality check predicate on the "theme_preference" field. It's identical to ThemePreferenceEQ.
func ThemePreference(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldThemePreference, v))
}

// EmailVerified applies equality check predicate on the "email_verified" field. It's identical to EmailVerifiedEQ.
func EmailVerified(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerified, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// PlayerNameEQ applies the EQ predicate on the "player_name" field.
func PlayerNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPlayerName, v))
}

// PlayerNameNEQ applies the NEQ predicate on the "player_name" field.
func PlayerNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPlayerName, v))
}

// PlayerNameIn applies the In predicate on the "player_name" field.
func PlayerNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPlayerName, vs...))
}

// PlayerNameNotIn applies the NotIn predicate on the "player_name" field.
func PlayerNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPlayerName, vs...))
}

// PlayerNameGT applies the GT predicate on the "player_name" field.
func PlayerNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPlayerName, v))
}

// PlayerNameGTE applies the GTE predicate on the "player_name" field.
func PlayerNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPlayerName, v))
}

// PlayerNameLT applies the LT predicate on the "player_name" field.
func PlayerNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPlayerName, v))
}

// PlayerNameLTE applies the LTE predicate on the "player_name" field.
func PlayerNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPlayerName, v))
}

// PlayerNameContains applies the Contains predicate on the "player_name" field.
func PlayerNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPlayerName, v))
}

// PlayerNameHasPrefix applies the HasPrefix predicate on the "player_name" field.
func PlayerNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPlayerName, v))
}

// PlayerNameHasSuffix applies the HasSuffix predicate on the "player_name" field.
func PlayerNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPlayerName, v))
}

// PlayerNameEqualFold applies the EqualFold predicate on the "player_name" field.
func PlayerNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPlayerName, v))
}

// PlayerNameContainsFold applies the ContainsFold predicate on the "player_name" field.
func PlayerNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPlayerName, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLevel, v))
}

// XpEQ applies the EQ predicate on the "xp" field.
func XpEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// XpNEQ applies the NEQ predicate on the "xp" field.
func XpNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldXp, v))
}

// XpIn applies the In predicate on the "xp" field.
func XpIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldXp, vs...))
}

// XpNotIn applies the NotIn predicate on the "xp" field.
func XpNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldXp, vs...))
}

// XpGT applies the GT predicate on the "xp" field.
func XpGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldXp, v))
}

// XpGTE applies the GTE predicate on the "xp" field.
func XpGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldXp, v))
}

// XpLT applies the LT predicate on the "xp" field.
func XpLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldXp, v))
}

// XpLTE applies the LTE predicate on the "xp" field.
func XpLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldXp, v))
}

// MaxXpEQ applies the EQ predicate on the "max_xp" field.
func MaxXpEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxXp, v))
}

// MaxXpNEQ applies the NEQ predicate on the "max_xp" field.
func MaxXpNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMaxXp, v))
}

// MaxXpIn applies the In predicate on the "max_xp" field.
func MaxXpIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldMaxXp, vs...))
}

// MaxXpNotIn applies the NotIn predicate on the "max_xp" field.
func MaxXpNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMaxXp, vs...))
}

// MaxXpGT applies the GT predicate on the "max_xp" field.
func MaxXpGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldMaxXp, v))
}

// MaxXpGTE applies the GTE predicate on the "max_xp" field.
func MaxXpGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMaxXp, v))
}

// MaxXpLT applies the LT predicate on the "max_xp" field.
func MaxXpLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldMaxXp, v))
}

// MaxXpLTE applies the LTE predicate on the "max_xp" field.
func MaxXpLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMaxXp, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTitle, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTags))
}

// ReadArticleCountEQ applies the EQ predicate on the "read_article_count" field.
func ReadArticleCountEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReadArticleCount, v))
}

// ReadArticleCountNEQ applies the NEQ predicate on the "read_article_count" field.
func ReadArticleCountNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldReadArticleCount, v))
}

// ReadArticleCountIn applies the In predicate on the "read_article_count" field.
func ReadArticleCountIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldReadArticleCount, vs...))
}

// ReadArticleCountNotIn applies the NotIn predicate on the "read_article_count" field.
func ReadArticleCountNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldReadArticleCount, vs...))
}

// ReadArticleCountGT applies the GT predicate on the "read_article_count" field.
func ReadArticleCountGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldReadArticleCount, v))
}

// ReadArticleCountGTE applies the GTE predicate on the "read_article_count" field.
func ReadArticleCountGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldReadArticleCount, v))
}

// ReadArticleCountLT applies the LT predicate on the "read_article_count" field.
func ReadArticleCountLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldReadArticleCount, v))
}

// ReadArticleCountLTE applies the LTE predicate on the "read_article_count" field.
func ReadArticleCountLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldReadArticleCount, v))
}

// LoginDaysEQ applies the EQ predicate on the "login_days" field.
func LoginDaysEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginDays, v))
}

// LoginDaysNEQ applies the NEQ predicate on the "login_days" field.
func LoginDaysNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLoginDays, v))
}

// LoginDaysIn applies the In predicate on the "login_days" field.
func LoginDaysIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldLoginDays, vs...))
}

// LoginDaysNotIn applies the NotIn predicate on the "login_days" field.
func LoginDaysNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLoginDays, vs...))
}

// LoginDaysGT applies the GT predicate on the "login_days" field.
func LoginDaysGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldLoginDays, v))
}

// LoginDaysGTE applies the GTE predicate on the "login_days" field.
func LoginDaysGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLoginDays, v))
}

// LoginDaysLT applies the LT predicate on the "login_days" field.
func LoginDaysLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldLoginDays, v))
}

// LoginDaysLTE applies the LTE predicate on the "login_days" field.
func LoginDaysLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLoginDays, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// ThemePreferenceEQ applies the EQ predicate on the "theme_preference" field.
func ThemePreferenceEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldThemePreference, v))
}

// ThemePreferenceNEQ applies the NEQ predicate on the "theme_preference" field.
func ThemePreferenceNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldThemePreference, v))
}

// ThemePreferenceIn applies the In predicate on the "theme_preference" field.
func ThemePreferenceIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldThemePreference, vs...))
}

// ThemePreferenceNotIn applies the NotIn predicate on the "theme_preference" field.
func ThemePreferenceNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldThemePreference, vs...))
}

// ThemePreferenceGT applies the GT predicate on the "theme_preference" field.
func ThemePreferenceGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldThemePreference, v))
}

// ThemePreferenceGTE applies the GTE predicate on the "theme_preference" field.
func ThemePreferenceGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldThemePreference, v))
}

// ThemePreferenceLT applies the LT predicate on the "theme_preference" field.
func ThemePreferenceLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldThemePreference, v))
}

// ThemePreferenceLTE applies the LTE predicate on the "theme_preference" field.
func ThemePreferenceLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldThemePreference, v))
}

// ThemePreferenceContains applies the Contains predicate on the "theme_preference" field.
func ThemePreferenceContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldThemePreference, v))
}

// ThemePreferenceHasPrefix applies the HasPrefix predicate on the "theme_preference" field.
func ThemePreferenceHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldThemePreference, v))
}

// ThemePreferenceHasSuffix applies the HasSuffix predicate on the "theme_preference" field.
func ThemePreferenceHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldThemePreference, v))
}

// ThemePreferenceEqualFold applies the EqualFold predicate on the "theme_preference" field.
func ThemePreferenceEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldThemePreference, v))
}

// ThemePreferenceContainsFold applies the ContainsFold predicate on the "theme_preference" field.
func ThemePreferenceContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldThemePreference, v))
}

// EmailVerifiedEQ applies the EQ predicate on the "email_verified" field.
func EmailVerifiedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerified, v))
}

// EmailVerifiedNEQ applies the NEQ predicate on the "email_verified" field.
func EmailVerifiedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmailVerified, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastLoginAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
