// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/achievement"
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AchievementUpdate is the builder for updating Achievement entities.
type AchievementUpdate struct {
	config
	hooks    []Hook
	mutation *AchievementMutation
}

// Where appends a list predicates to the AchievementUpdate builder.
func (_u *AchievementUpdate) Where(ps ...predicate.Achievement) *AchievementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AchievementUpdate) SetUpdatedAt(v int64) *AchievementUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AchievementUpdate) AddUpdatedAt(v int64) *AchievementUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AchievementUpdate) SetName(v string) *AchievementUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AchievementUpdate) SetNillableName(v *string) *AchievementUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AchievementUpdate) SetDescription(v string) *AchievementUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AchievementUpdate) SetNillableDescription(v *string) *AchievementUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AchievementUpdate) SetIcon(v string) *AchievementUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AchievementUpdate) SetNillableIcon(v *string) *AchievementUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetConditionType sets the "condition_type" field.
func (_u *AchievementUpdate) SetConditionType(v string) *AchievementUpdate {
	_u.mutation.SetConditionType(v)
	return _u
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (_u *AchievementUpdate) SetNillableConditionType(v *string) *AchievementUpdate {
	if v != nil {
		_u.SetConditionType(*v)
	}
	return _u
}

// SetConditionValue sets the "condition_value" field.
func (_u *AchievementUpdate) SetConditionValue(v int) *AchievementUpdate {
	_u.mutation.ResetConditionValue()
	_u.mutation.SetConditionValue(v)
	return _u
}

// SetNillableConditionValue sets the "condition_value" field if the given value is not nil.
func (_u *AchievementUpdate) SetNillableConditionValue(v *int) *AchievementUpdate {
	if v != nil {
		_u.SetConditionValue(*v)
	}
	return _u
}

// AddConditionValue adds value to the "condition_value" field.
func (_u *AchievementUpdate) AddConditionValue(v int) *AchievementUpdate {
	_u.mutation.AddConditionValue(v)
	return _u
}

// Mutation returns the AchievementMutation object of the builder.
func (_u *AchievementUpdate) Mutation() *AchievementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AchievementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AchievementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AchievementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AchievementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AchievementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := achievement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AchievementUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := achievement.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Achievement.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := achievement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Achievement.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := achievement.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "Achievement.icon": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConditionType(); ok {
		if err := achievement.ConditionTypeValidator(v); err != nil {
			return &ValidationError{Name: "condition_type", err: fmt.Errorf(`ent: validator failed for field "Achievement.condition_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AchievementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(achievement.Table, achievement.Columns, sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(achievement.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(achievement.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(achievement.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(achievement.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(achievement.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionType(); ok {
		_spec.SetField(achievement.FieldConditionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionValue(); ok {
		_spec.SetField(achievement.FieldConditionValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConditionValue(); ok {
		_spec.AddField(achievement.FieldConditionValue, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{achievement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AchievementUpdateOne is the builder for updating a single Achievement entity.
type AchievementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AchievementMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AchievementUpdateOne) SetUpdatedAt(v int64) *AchievementUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AchievementUpdateOne) AddUpdatedAt(v int64) *AchievementUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AchievementUpdateOne) SetName(v string) *AchievementUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AchievementUpdateOne) SetNillableName(v *string) *AchievementUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AchievementUpdateOne) SetDescription(v string) *AchievementUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AchievementUpdateOne) SetNillableDescription(v *string) *AchievementUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AchievementUpdateOne) SetIcon(v string) *AchievementUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AchievementUpdateOne) SetNillableIcon(v *string) *AchievementUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetConditionType sets the "condition_type" field.
func (_u *AchievementUpdateOne) SetConditionType(v string) *AchievementUpdateOne {
	_u.mutation.SetConditionType(v)
	return _u
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (_u *AchievementUpdateOne) SetNillableConditionType(v *string) *AchievementUpdateOne {
	if v != nil {
		_u.SetConditionType(*v)
	}
	return _u
}

// SetConditionValue sets the "condition_value" field.
func (_u *AchievementUpdateOne) SetConditionValue(v int) *AchievementUpdateOne {
	_u.mutation.ResetConditionValue()
	_u.mutation.SetConditionValue(v)
	return _u
}

// SetNillableConditionValue sets the "condition_value" field if the given value is not nil.
func (_u *AchievementUpdateOne) SetNillableConditionValue(v *int) *AchievementUpdateOne {
	if v != nil {
		_u.SetConditionValue(*v)
	}
	return _u
}

// AddConditionValue adds value to the "condition_value" field.
func (_u *AchievementUpdateOne) AddConditionValue(v int) *AchievementUpdateOne {
	_u.mutation.AddConditionValue(v)
	return _u
}

// Mutation returns the AchievementMutation object of the builder.
func (_u *AchievementUpdateOne) Mutation() *AchievementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AchievementUpdate builder.
func (_u *AchievementUpdateOne) Where(ps ...predicate.Achievement) *AchievementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AchievementUpdateOne) Select(field string, fields ...string) *AchievementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Achievement entity.
func (_u *AchievementUpdateOne) Save(ctx context.Context) (*Achievement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AchievementUpdateOne) SaveX(ctx context.Context) *Achievement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AchievementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AchievementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AchievementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := achievement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AchievementUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := achievement.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Achievement.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := achievement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Achievement.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := achievement.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "Achievement.icon": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConditionType(); ok {
		if err := achievement.ConditionTypeValidator(v); err != nil {
			return &ValidationError{Name: "condition_type", err: fmt.Errorf(`ent: validator failed for field "Achievement.condition_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AchievementUpdateOne) sqlSave(ctx context.Context) (_node *Achievement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(achievement.Table, achievement.Columns, sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Achievement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, achievement.FieldID)
		for _, f := range fields {
			if !achievement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != achievement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(achievement.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(achievement.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(achievement.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(achievement.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(achievement.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionType(); ok {
		_spec.SetField(achievement.FieldConditionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionValue(); ok {
		_spec.SetField(achievement.FieldConditionValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConditionValue(); ok {
		_spec.AddField(achievement.FieldConditionValue, field.TypeInt, value)
	}
	_node = &Achievement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{achievement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
