// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"isolo-news/internal/ent/articleread"
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleReadDelete is the builder for deleting a ArticleRead entity.
type ArticleReadDelete struct {
	config
	hooks    []Hook
	mutation *ArticleReadMutation
}

// Where appends a list predicates to the ArticleReadDelete builder.
func (_d *ArticleReadDelete) Where(ps ...predicate.ArticleRead) *ArticleReadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ArticleReadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArticleReadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ArticleReadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(articleread.Table, sqlgraph.NewFieldSpec(articleread.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ArticleReadDeleteOne is the builder for deleting a single ArticleRead entity.
type ArticleReadDeleteOne struct {
	_d *ArticleReadDelete
}

// Where appends a list predicates to the ArticleReadDelete builder.
func (_d *ArticleReadDeleteOne) Where(ps ...predicate.ArticleRead) *ArticleReadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ArticleReadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{articleread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArticleReadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
