// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/article"
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleUpdate) SetUpdatedAt(v int64) *ArticleUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ArticleUpdate) AddUpdatedAt(v int64) *ArticleUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdate) SetTitle(v string) *ArticleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableTitle(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleUpdate) SetSummary(v string) *ArticleUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSummary(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ArticleUpdate) ClearSummary() *ArticleUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdate) SetContent(v string) *ArticleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableContent(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdate) ClearContent() *ArticleUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ArticleUpdate) SetCategoryID(v string) *ArticleUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableCategoryID(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ArticleUpdate) SetAuthor(v string) *ArticleUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableAuthor(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArticleUpdate) SetPublishedAt(v int64) *ArticleUpdate {
	_u.mutation.ResetPublishedAt()
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillablePublishedAt(v *int64) *ArticleUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// AddPublishedAt adds value to the "published_at" field.
func (_u *ArticleUpdate) AddPublishedAt(v int64) *ArticleUpdate {
	_u.mutation.AddPublishedAt(v)
	return _u
}

// SetReadTime sets the "read_time" field.
func (_u *ArticleUpdate) SetReadTime(v int) *ArticleUpdate {
	_u.mutation.ResetReadTime()
	_u.mutation.SetReadTime(v)
	return _u
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableReadTime(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetReadTime(*v)
	}
	return _u
}

// AddReadTime adds value to the "read_time" field.
func (_u *ArticleUpdate) AddReadTime(v int) *ArticleUpdate {
	_u.mutation.AddReadTime(v)
	return _u
}

// SetXpReward sets the "xp_reward" field.
func (_u *ArticleUpdate) SetXpReward(v int) *ArticleUpdate {
	_u.mutation.ResetXpReward()
	_u.mutation.SetXpReward(v)
	return _u
}

// SetNillableXpReward sets the "xp_reward" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableXpReward(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetXpReward(*v)
	}
	return _u
}

// AddXpReward adds value to the "xp_reward" field.
func (_u *ArticleUpdate) AddXpReward(v int) *ArticleUpdate {
	_u.mutation.AddXpReward(v)
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *ArticleUpdate) SetImageURL(v string) *ArticleUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableImageURL(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *ArticleUpdate) ClearImageURL() *ArticleUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ArticleUpdate) SetTags(v []string) *ArticleUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ArticleUpdate) AppendTags(v []string) *ArticleUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ArticleUpdate) ClearTags() *ArticleUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *ArticleUpdate) SetIsFeatured(v bool) *ArticleUpdate {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableIsFeatured(v *bool) *ArticleUpdate {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ArticleUpdate) SetSourceID(v string) *ArticleUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSourceID(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ArticleUpdate) ClearSourceID() *ArticleUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *ArticleUpdate) SetSourceURL(v string) *ArticleUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSourceURL(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ArticleUpdate) SetSourceName(v string) *ArticleUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSourceName(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ArticleUpdate) ClearSourceName() *ArticleUpdate {
	_u.mutation.ClearSourceName()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *ArticleUpdate) SetViewCount(v int) *ArticleUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableViewCount(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *ArticleUpdate) AddViewCount(v int) *ArticleUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *ArticleUpdate) SetCommentCount(v int) *ArticleUpdate {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableCommentCount(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *ArticleUpdate) AddCommentCount(v int) *ArticleUpdate {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *ArticleUpdate) SetLikeCount(v int) *ArticleUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableLikeCount(v *int) *ArticleUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *ArticleUpdate) AddLikeCount(v int) *ArticleUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ArticleUpdate) SetCollectedAt(v int64) *ArticleUpdate {
	_u.mutation.ResetCollectedAt()
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableCollectedAt(v *int64) *ArticleUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// AddCollectedAt adds value to the "collected_at" field.
func (_u *ArticleUpdate) AddCollectedAt(v int64) *ArticleUpdate {
	_u.mutation.AddCollectedAt(v)
	return _u
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdate) Mutation() *ArticleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := article.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Article.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := article.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Article.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := article.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Article.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURL(); ok {
		if err := article.SourceURLValidator(v); err != nil {
			return &ValidationError{Name: "source_url", err: fmt.Errorf(`ent: validator failed for field "Article.source_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(article.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(article.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(article.FieldCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedAt(); ok {
		_spec.AddField(article.FieldPublishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadTime(); ok {
		_spec.SetField(article.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadTime(); ok {
		_spec.AddField(article.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.XpReward(); ok {
		_spec.SetField(article.FieldXpReward, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXpReward(); ok {
		_spec.AddField(article.FieldXpReward, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(article.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(article.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(article.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(article.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(article.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(article.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(article.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(article.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(article.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(article.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(article.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(article.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(article.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(article.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(article.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(article.FieldCollectedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectedAt(); ok {
		_spec.AddField(article.FieldCollectedAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleUpdateOne) SetUpdatedAt(v int64) *ArticleUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ArticleUpdateOne) AddUpdatedAt(v int64) *ArticleUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleUpdateOne) SetTitle(v string) *ArticleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableTitle(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleUpdateOne) SetSummary(v string) *ArticleUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSummary(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ArticleUpdateOne) ClearSummary() *ArticleUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdateOne) SetContent(v string) *ArticleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableContent(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdateOne) ClearContent() *ArticleUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ArticleUpdateOne) SetCategoryID(v string) *ArticleUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableCategoryID(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ArticleUpdateOne) SetAuthor(v string) *ArticleUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableAuthor(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArticleUpdateOne) SetPublishedAt(v int64) *ArticleUpdateOne {
	_u.mutation.ResetPublishedAt()
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillablePublishedAt(v *int64) *ArticleUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// AddPublishedAt adds value to the "published_at" field.
func (_u *ArticleUpdateOne) AddPublishedAt(v int64) *ArticleUpdateOne {
	_u.mutation.AddPublishedAt(v)
	return _u
}

// SetReadTime sets the "read_time" field.
func (_u *ArticleUpdateOne) SetReadTime(v int) *ArticleUpdateOne {
	_u.mutation.ResetReadTime()
	_u.mutation.SetReadTime(v)
	return _u
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableReadTime(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetReadTime(*v)
	}
	return _u
}

// AddReadTime adds value to the "read_time" field.
func (_u *ArticleUpdateOne) AddReadTime(v int) *ArticleUpdateOne {
	_u.mutation.AddReadTime(v)
	return _u
}

// SetXpReward sets the "xp_reward" field.
func (_u *ArticleUpdateOne) SetXpReward(v int) *ArticleUpdateOne {
	_u.mutation.ResetXpReward()
	_u.mutation.SetXpReward(v)
	return _u
}

// SetNillableXpReward sets the "xp_reward" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableXpReward(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetXpReward(*v)
	}
	return _u
}

// AddXpReward adds value to the "xp_reward" field.
func (_u *ArticleUpdateOne) AddXpReward(v int) *ArticleUpdateOne {
	_u.mutation.AddXpReward(v)
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *ArticleUpdateOne) SetImageURL(v string) *ArticleUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableImageURL(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *ArticleUpdateOne) ClearImageURL() *ArticleUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ArticleUpdateOne) SetTags(v []string) *ArticleUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ArticleUpdateOne) AppendTags(v []string) *ArticleUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ArticleUpdateOne) ClearTags() *ArticleUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *ArticleUpdateOne) SetIsFeatured(v bool) *ArticleUpdateOne {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableIsFeatured(v *bool) *ArticleUpdateOne {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ArticleUpdateOne) SetSourceID(v string) *ArticleUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSourceID(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ArticleUpdateOne) ClearSourceID() *ArticleUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *ArticleUpdateOne) SetSourceURL(v string) *ArticleUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSourceURL(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ArticleUpdateOne) SetSourceName(v string) *ArticleUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSourceName(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ArticleUpdateOne) ClearSourceName() *ArticleUpdateOne {
	_u.mutation.ClearSourceName()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *ArticleUpdateOne) SetViewCount(v int) *ArticleUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableViewCount(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *ArticleUpdateOne) AddViewCount(v int) *ArticleUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *ArticleUpdateOne) SetCommentCount(v int) *ArticleUpdateOne {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableCommentCount(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *ArticleUpdateOne) AddCommentCount(v int) *ArticleUpdateOne {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *ArticleUpdateOne) SetLikeCount(v int) *ArticleUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableLikeCount(v *int) *ArticleUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *ArticleUpdateOne) AddLikeCount(v int) *ArticleUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ArticleUpdateOne) SetCollectedAt(v int64) *ArticleUpdateOne {
	_u.mutation.ResetCollectedAt()
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableCollectedAt(v *int64) *ArticleUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// AddCollectedAt adds value to the "collected_at" field.
func (_u *ArticleUpdateOne) AddCollectedAt(v int64) *ArticleUpdateOne {
	_u.mutation.AddCollectedAt(v)
	return _u
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdateOne) Mutation() *ArticleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Article entity.
func (_u *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := article.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Article.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := article.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Article.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageURL(); ok {
		if err := article.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Article.image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURL(); ok {
		if err := article.SourceURLValidator(v); err != nil {
			return &ValidationError{Name: "source_url", err: fmt.Errorf(`ent: validator failed for field "Article.source_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(article.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(article.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(article.FieldCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedAt(); ok {
		_spec.AddField(article.FieldPublishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadTime(); ok {
		_spec.SetField(article.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadTime(); ok {
		_spec.AddField(article.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.XpReward(); ok {
		_spec.SetField(article.FieldXpReward, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXpReward(); ok {
		_spec.AddField(article.FieldXpReward, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(article.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(article.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(article.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(article.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(article.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(article.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(article.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(article.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(article.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(article.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(article.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(article.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(article.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(article.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(article.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(article.FieldCollectedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectedAt(); ok {
		_spec.AddField(article.FieldCollectedAt, field.TypeInt64, value)
	}
	_node = &Article{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
