// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/articleread"
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleReadUpdate is the builder for updating ArticleRead entities.
type ArticleReadUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleReadMutation
}

// Where appends a list predicates to the ArticleReadUpdate builder.
func (_u *ArticleReadUpdate) Where(ps ...predicate.ArticleRead) *ArticleReadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleReadUpdate) SetUpdatedAt(v int64) *ArticleReadUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ArticleReadUpdate) AddUpdatedAt(v int64) *ArticleReadUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ArticleReadUpdate) SetUserID(v string) *ArticleReadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ArticleReadUpdate) SetNillableUserID(v *string) *ArticleReadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleReadUpdate) SetArticleID(v string) *ArticleReadUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleReadUpdate) SetNillableArticleID(v *string) *ArticleReadUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *ArticleReadUpdate) SetReadAt(v int64) *ArticleReadUpdate {
	_u.mutation.ResetReadAt()
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *ArticleReadUpdate) SetNillableReadAt(v *int64) *ArticleReadUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// AddReadAt adds value to the "read_at" field.
func (_u *ArticleReadUpdate) AddReadAt(v int64) *ArticleReadUpdate {
	_u.mutation.AddReadAt(v)
	return _u
}

// Mutation returns the ArticleReadMutation object of the builder.
func (_u *ArticleReadUpdate) Mutation() *ArticleReadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleReadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleReadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleReadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleReadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleReadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := articleread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleReadUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := articleread.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ArticleRead.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := articleread.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "ArticleRead.article_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ArticleReadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articleread.Table, articleread.Columns, sqlgraph.NewFieldSpec(articleread.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(articleread.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(articleread.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(articleread.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(articleread.FieldArticleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(articleread.FieldReadAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadAt(); ok {
		_spec.AddField(articleread.FieldReadAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articleread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleReadUpdateOne is the builder for updating a single ArticleRead entity.
type ArticleReadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleReadMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleReadUpdateOne) SetUpdatedAt(v int64) *ArticleReadUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ArticleReadUpdateOne) AddUpdatedAt(v int64) *ArticleReadUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ArticleReadUpdateOne) SetUserID(v string) *ArticleReadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ArticleReadUpdateOne) SetNillableUserID(v *string) *ArticleReadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleReadUpdateOne) SetArticleID(v string) *ArticleReadUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleReadUpdateOne) SetNillableArticleID(v *string) *ArticleReadUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *ArticleReadUpdateOne) SetReadAt(v int64) *ArticleReadUpdateOne {
	_u.mutation.ResetReadAt()
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *ArticleReadUpdateOne) SetNillableReadAt(v *int64) *ArticleReadUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// AddReadAt adds value to the "read_at" field.
func (_u *ArticleReadUpdateOne) AddReadAt(v int64) *ArticleReadUpdateOne {
	_u.mutation.AddReadAt(v)
	return _u
}

// Mutation returns the ArticleReadMutation object of the builder.
func (_u *ArticleReadUpdateOne) Mutation() *ArticleReadMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArticleReadUpdate builder.
func (_u *ArticleReadUpdateOne) Where(ps ...predicate.ArticleRead) *ArticleReadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleReadUpdateOne) Select(field string, fields ...string) *ArticleReadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ArticleRead entity.
func (_u *ArticleReadUpdateOne) Save(ctx context.Context) (*ArticleRead, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleReadUpdateOne) SaveX(ctx context.Context) *ArticleRead {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleReadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleReadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleReadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := articleread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleReadUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := articleread.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ArticleRead.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := articleread.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "ArticleRead.article_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ArticleReadUpdateOne) sqlSave(ctx context.Context) (_node *ArticleRead, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articleread.Table, articleread.Columns, sqlgraph.NewFieldSpec(articleread.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArticleRead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articleread.FieldID)
		for _, f := range fields {
			if !articleread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != articleread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(articleread.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(articleread.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(articleread.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(articleread.FieldArticleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(articleread.FieldReadAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadAt(); ok {
		_spec.AddField(articleread.FieldReadAt, field.TypeInt64, value)
	}
	_node = &ArticleRead{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articleread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
