// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/like"
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeUpdate is the builder for updating Like entities.
type LikeUpdate struct {
	config
	hooks    []Hook
	mutation *LikeMutation
}

// Where appends a list predicates to the LikeUpdate builder.
func (_u *LikeUpdate) Where(ps ...predicate.Like) *LikeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LikeUpdate) SetUpdatedAt(v int64) *LikeUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *LikeUpdate) AddUpdatedAt(v int64) *LikeUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LikeUpdate) SetUserID(v string) *LikeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableUserID(v *string) *LikeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *LikeUpdate) SetArticleID(v string) *LikeUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableArticleID(v *string) *LikeUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// Mutation returns the LikeMutation object of the builder.
func (_u *LikeUpdate) Mutation() *LikeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LikeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LikeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LikeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := like.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := like.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Like.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := like.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "Like.article_id": %w`, err)}
		}
	}
	return nil
}

func (_u *LikeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(like.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(like.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(like.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(like.FieldArticleID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LikeUpdateOne is the builder for updating a single Like entity.
type LikeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LikeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LikeUpdateOne) SetUpdatedAt(v int64) *LikeUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *LikeUpdateOne) AddUpdatedAt(v int64) *LikeUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LikeUpdateOne) SetUserID(v string) *LikeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableUserID(v *string) *LikeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *LikeUpdateOne) SetArticleID(v string) *LikeUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableArticleID(v *string) *LikeUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// Mutation returns the LikeMutation object of the builder.
func (_u *LikeUpdateOne) Mutation() *LikeMutation {
	return _u.mutation
}

// Where appends a list predicates to the LikeUpdate builder.
func (_u *LikeUpdateOne) Where(ps ...predicate.Like) *LikeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LikeUpdateOne) Select(field string, fields ...string) *LikeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Like entity.
func (_u *LikeUpdateOne) Save(ctx context.Context) (*Like, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeUpdateOne) SaveX(ctx context.Context) *Like {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LikeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LikeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := like.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := like.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Like.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := like.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "Like.article_id": %w`, err)}
		}
	}
	return nil
}

func (_u *LikeUpdateOne) sqlSave(ctx context.Context) (_node *Like, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Like.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, like.FieldID)
		for _, f := range fields {
			if !like.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != like.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(like.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(like.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(like.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(like.FieldArticleID, field.TypeString, value)
	}
	_node = &Like{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
