// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/quest"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestCreate is the builder for creating a Quest entity.
type QuestCreate struct {
	config
	mutation *QuestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuestCreate) SetCreatedAt(v int64) *QuestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuestCreate) SetNillableCreatedAt(v *int64) *QuestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuestCreate) SetUpdatedAt(v int64) *QuestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuestCreate) SetNillableUpdatedAt(v *int64) *QuestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *QuestCreate) SetTitle(v string) *QuestCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *QuestCreate) SetDescription(v string) *QuestCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetXpReward sets the "xp_reward" field.
func (_c *QuestCreate) SetXpReward(v int) *QuestCreate {
	_c.mutation.SetXpReward(v)
	return _c
}

// SetNillableXpReward sets the "xp_reward" field if the given value is not nil.
func (_c *QuestCreate) SetNillableXpReward(v *int) *QuestCreate {
	if v != nil {
		_c.SetXpReward(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *QuestCreate) SetTarget(v int) *QuestCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *QuestCreate) SetNillableTarget(v *int) *QuestCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetQuestType sets the "quest_type" field.
func (_c *QuestCreate) SetQuestType(v string) *QuestCreate {
	_c.mutation.SetQuestType(v)
	return _c
}

// SetIsDaily sets the "is_daily" field.
func (_c *QuestCreate) SetIsDaily(v bool) *QuestCreate {
	_c.mutation.SetIsDaily(v)
	return _c
}

// SetNillableIsDaily sets the "is_daily" field if the given value is not nil.
func (_c *QuestCreate) SetNillableIsDaily(v *bool) *QuestCreate {
	if v != nil {
		_c.SetIsDaily(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuestCreate) SetID(v string) *QuestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QuestCreate) SetNillableID(v *string) *QuestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the QuestMutation object of the builder.
func (_c *QuestCreate) Mutation() *QuestMutation {
	return _c.mutation
}

// Save creates the Quest in the database.
func (_c *QuestCreate) Save(ctx context.Context) (*Quest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestCreate) SaveX(ctx context.Context) *Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.XpReward(); !ok {
		v := quest.DefaultXpReward
		_c.mutation.SetXpReward(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := quest.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.IsDaily(); !ok {
		v := quest.DefaultIsDaily
		_c.mutation.SetIsDaily(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := quest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Quest.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Quest.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := quest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Quest.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Quest.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := quest.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Quest.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.XpReward(); !ok {
		return &ValidationError{Name: "xp_reward", err: errors.New(`ent: missing required field "Quest.xp_reward"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Quest.target"`)}
	}
	if _, ok := _c.mutation.QuestType(); !ok {
		return &ValidationError{Name: "quest_type", err: errors.New(`ent: missing required field "Quest.quest_type"`)}
	}
	if v, ok := _c.mutation.QuestType(); ok {
		if err := quest.QuestTypeValidator(v); err != nil {
			return &ValidationError{Name: "quest_type", err: fmt.Errorf(`ent: validator failed for field "Quest.quest_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDaily(); !ok {
		return &ValidationError{Name: "is_daily", err: errors.New(`ent: missing required field "Quest.is_daily"`)}
	}
	return nil
}

func (_c *QuestCreate) sqlSave(ctx context.Context) (*Quest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Quest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestCreate) createSpec() (*Quest, *sqlgraph.CreateSpec) {
	var (
		_node = &Quest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quest.Table, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quest.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quest.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(quest.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(quest.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.XpReward(); ok {
		_spec.SetField(quest.FieldXpReward, field.TypeInt, value)
		_node.XpReward = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(quest.FieldTarget, field.TypeInt, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.QuestType(); ok {
		_spec.SetField(quest.FieldQuestType, field.TypeString, value)
		_node.QuestType = value
	}
	if value, ok := _c.mutation.IsDaily(); ok {
		_spec.SetField(quest.FieldIsDaily, field.TypeBool, value)
		_node.IsDaily = value
	}
	return _node, _spec
}

// QuestCreateBulk is the builder for creating many Quest entities in bulk.
type QuestCreateBulk struct {
	config
	err      error
	builders []*QuestCreate
}

// Save creates the Quest entities in the database.
func (_c *QuestCreateBulk) Save(ctx context.Context) ([]*Quest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestCreateBulk) SaveX(ctx context.Context) []*Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
