// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/predicate"
	"isolo-news/internal/ent/schedulesetting"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleSettingUpdate is the builder for updating ScheduleSetting entities.
type ScheduleSettingUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleSettingMutation
}

// Where appends a list predicates to the ScheduleSettingUpdate builder.
func (_u *ScheduleSettingUpdate) Where(ps ...predicate.ScheduleSetting) *ScheduleSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleSettingUpdate) SetUpdatedAt(v int64) *ScheduleSettingUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ScheduleSettingUpdate) AddUpdatedAt(v int64) *ScheduleSettingUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ScheduleSettingUpdate) SetCategoryID(v string) *ScheduleSettingUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ScheduleSettingUpdate) SetNillableCategoryID(v *string) *ScheduleSettingUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *ScheduleSettingUpdate) SetCronExpression(v string) *ScheduleSettingUpdate {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *ScheduleSettingUpdate) SetNillableCronExpression(v *string) *ScheduleSettingUpdate {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ScheduleSettingUpdate) SetIsActive(v bool) *ScheduleSettingUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ScheduleSettingUpdate) SetNillableIsActive(v *bool) *ScheduleSettingUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the ScheduleSettingMutation object of the builder.
func (_u *ScheduleSettingUpdate) Mutation() *ScheduleSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulesetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleSettingUpdate) check() error {
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := schedulesetting.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "ScheduleSetting.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := schedulesetting.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "ScheduleSetting.cron_expression": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduleSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulesetting.Table, schedulesetting.Columns, sqlgraph.NewFieldSpec(schedulesetting.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulesetting.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(schedulesetting.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(schedulesetting.FieldCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(schedulesetting.FieldCronExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(schedulesetting.FieldIsActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleSettingUpdateOne is the builder for updating a single ScheduleSetting entity.
type ScheduleSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleSettingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleSettingUpdateOne) SetUpdatedAt(v int64) *ScheduleSettingUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ScheduleSettingUpdateOne) AddUpdatedAt(v int64) *ScheduleSettingUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ScheduleSettingUpdateOne) SetCategoryID(v string) *ScheduleSettingUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ScheduleSettingUpdateOne) SetNillableCategoryID(v *string) *ScheduleSettingUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *ScheduleSettingUpdateOne) SetCronExpression(v string) *ScheduleSettingUpdateOne {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *ScheduleSettingUpdateOne) SetNillableCronExpression(v *string) *ScheduleSettingUpdateOne {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ScheduleSettingUpdateOne) SetIsActive(v bool) *ScheduleSettingUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ScheduleSettingUpdateOne) SetNillableIsActive(v *bool) *ScheduleSettingUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the ScheduleSettingMutation object of the builder.
func (_u *ScheduleSettingUpdateOne) Mutation() *ScheduleSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScheduleSettingUpdate builder.
func (_u *ScheduleSettingUpdateOne) Where(ps ...predicate.ScheduleSetting) *ScheduleSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleSettingUpdateOne) Select(field string, fields ...string) *ScheduleSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduleSetting entity.
func (_u *ScheduleSettingUpdateOne) Save(ctx context.Context) (*ScheduleSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleSettingUpdateOne) SaveX(ctx context.Context) *ScheduleSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulesetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleSettingUpdateOne) check() error {
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := schedulesetting.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "ScheduleSetting.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := schedulesetting.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "ScheduleSetting.cron_expression": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduleSettingUpdateOne) sqlSave(ctx context.Context) (_node *ScheduleSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulesetting.Table, schedulesetting.Columns, sqlgraph.NewFieldSpec(schedulesetting.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduleSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulesetting.FieldID)
		for _, f := range fields {
			if !schedulesetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulesetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulesetting.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(schedulesetting.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(schedulesetting.FieldCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(schedulesetting.FieldCronExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(schedulesetting.FieldIsActive, field.TypeBool, value)
	}
	_node = &ScheduleSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
