// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/source"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SourceCreate is the builder for creating a Source entity.
type SourceCreate struct {
	config
	mutation *SourceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SourceCreate) SetCreatedAt(v int64) *SourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableCreatedAt(v *int64) *SourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SourceCreate) SetUpdatedAt(v int64) *SourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableUpdatedAt(v *int64) *SourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SourceCreate) SetName(v string) *SourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFeedURL sets the "feed_url" field.
func (_c *SourceCreate) SetFeedURL(v string) *SourceCreate {
	_c.mutation.SetFeedURL(v)
	return _c
}

// SetSiteURL sets the "site_url" field.
func (_c *SourceCreate) SetSiteURL(v string) *SourceCreate {
	_c.mutation.SetSiteURL(v)
	return _c
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_c *SourceCreate) SetNillableSiteURL(v *string) *SourceCreate {
	if v != nil {
		_c.SetSiteURL(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *SourceCreate) SetCategoryID(v string) *SourceCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *SourceCreate) SetIsActive(v bool) *SourceCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *SourceCreate) SetNillableIsActive(v *bool) *SourceCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetFetchInterval sets the "fetch_interval" field.
func (_c *SourceCreate) SetFetchInterval(v int) *SourceCreate {
	_c.mutation.SetFetchInterval(v)
	return _c
}

// SetNillableFetchInterval sets the "fetch_interval" field if the given value is not nil.
func (_c *SourceCreate) SetNillableFetchInterval(v *int) *SourceCreate {
	if v != nil {
		_c.SetFetchInterval(*v)
	}
	return _c
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_c *SourceCreate) SetLastFetchedAt(v int64) *SourceCreate {
	_c.mutation.SetLastFetchedAt(v)
	return _c
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableLastFetchedAt(v *int64) *SourceCreate {
	if v != nil {
		_c.SetLastFetchedAt(*v)
	}
	return _c
}

// SetLastFailedAt sets the "last_failed_at" field.
func (_c *SourceCreate) SetLastFailedAt(v int64) *SourceCreate {
	_c.mutation.SetLastFailedAt(v)
	return _c
}

// SetNillableLastFailedAt sets the "last_failed_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableLastFailedAt(v *int64) *SourceCreate {
	if v != nil {
		_c.SetLastFailedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *SourceCreate) SetLastError(v string) *SourceCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *SourceCreate) SetNillableLastError(v *string) *SourceCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetFailCount sets the "fail_count" field.
func (_c *SourceCreate) SetFailCount(v int) *SourceCreate {
	_c.mutation.SetFailCount(v)
	return _c
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_c *SourceCreate) SetNillableFailCount(v *int) *SourceCreate {
	if v != nil {
		_c.SetFailCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SourceCreate) SetID(v string) *SourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SourceCreate) SetNillableID(v *string) *SourceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SourceMutation object of the builder.
func (_c *SourceCreate) Mutation() *SourceMutation {
	return _c.mutation
}

// Save creates the Source in the database.
func (_c *SourceCreate) Save(ctx context.Context) (*Source, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceCreate) SaveX(ctx context.Context) *Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := source.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := source.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := source.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.FetchInterval(); !ok {
		v := source.DefaultFetchInterval
		_c.mutation.SetFetchInterval(v)
	}
	if _, ok := _c.mutation.FailCount(); !ok {
		v := source.DefaultFailCount
		_c.mutation.SetFailCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := source.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Source.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Source.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Source.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := source.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Source.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeedURL(); !ok {
		return &ValidationError{Name: "feed_url", err: errors.New(`ent: missing required field "Source.feed_url"`)}
	}
	if v, ok := _c.mutation.FeedURL(); ok {
		if err := source.FeedURLValidator(v); err != nil {
			return &ValidationError{Name: "feed_url", err: fmt.Errorf(`ent: validator failed for field "Source.feed_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "Source.category_id"`)}
	}
	if v, ok := _c.mutation.CategoryID(); ok {
		if err := source.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Source.category_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Source.is_active"`)}
	}
	if _, ok := _c.mutation.FetchInterval(); !ok {
		return &ValidationError{Name: "fetch_interval", err: errors.New(`ent: missing required field "Source.fetch_interval"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := source.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "Source.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailCount(); !ok {
		return &ValidationError{Name: "fail_count", err: errors.New(`ent: missing required field "Source.fail_count"`)}
	}
	return nil
}

func (_c *SourceCreate) sqlSave(ctx context.Context) (*Source, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Source.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceCreate) createSpec() (*Source, *sqlgraph.CreateSpec) {
	var (
		_node = &Source{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(source.Table, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(source.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FeedURL(); ok {
		_spec.SetField(source.FieldFeedURL, field.TypeString, value)
		_node.FeedURL = value
	}
	if value, ok := _c.mutation.SiteURL(); ok {
		_spec.SetField(source.FieldSiteURL, field.TypeString, value)
		_node.SiteURL = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(source.FieldCategoryID, field.TypeString, value)
		_node.CategoryID = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(source.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.FetchInterval(); ok {
		_spec.SetField(source.FieldFetchInterval, field.TypeInt, value)
		_node.FetchInterval = value
	}
	if value, ok := _c.mutation.LastFetchedAt(); ok {
		_spec.SetField(source.FieldLastFetchedAt, field.TypeInt64, value)
		_node.LastFetchedAt = value
	}
	if value, ok := _c.mutation.LastFailedAt(); ok {
		_spec.SetField(source.FieldLastFailedAt, field.TypeInt64, value)
		_node.LastFailedAt = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(source.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.FailCount(); ok {
		_spec.SetField(source.FieldFailCount, field.TypeInt, value)
		_node.FailCount = value
	}
	return _node, _spec
}

// SourceCreateBulk is the builder for creating many Source entities in bulk.
type SourceCreateBulk struct {
	config
	err      error
	builders []*SourceCreate
}

// Save creates the Source entities in the database.
func (_c *SourceCreateBulk) Save(ctx context.Context) ([]*Source, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Source, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceCreateBulk) SaveX(ctx context.Context) []*Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
