// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/userquest"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserQuestCreate is the builder for creating a UserQuest entity.
type UserQuestCreate struct {
	config
	mutation *UserQuestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserQuestCreate) SetCreatedAt(v int64) *UserQuestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableCreatedAt(v *int64) *UserQuestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserQuestCreate) SetUpdatedAt(v int64) *UserQuestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableUpdatedAt(v *int64) *UserQuestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserQuestCreate) SetUserID(v string) *UserQuestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetQuestID sets the "quest_id" field.
func (_c *UserQuestCreate) SetQuestID(v string) *UserQuestCreate {
	_c.mutation.SetQuestID(v)
	return _c
}

// SetProgress sets the "progress" field.
func (_c *UserQuestCreate) SetProgress(v int) *UserQuestCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableProgress(v *int) *UserQuestCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserQuestCreate) SetStatus(v string) *UserQuestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableStatus(v *string) *UserQuestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDateAt sets the "date_at" field.
func (_c *UserQuestCreate) SetDateAt(v int64) *UserQuestCreate {
	_c.mutation.SetDateAt(v)
	return _c
}

// SetNillableDateAt sets the "date_at" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableDateAt(v *int64) *UserQuestCreate {
	if v != nil {
		_c.SetDateAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserQuestCreate) SetID(v string) *UserQuestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserQuestCreate) SetNillableID(v *string) *UserQuestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UserQuestMutation object of the builder.
func (_c *UserQuestCreate) Mutation() *UserQuestMutation {
	return _c.mutation
}

// Save creates the UserQuest in the database.
func (_c *UserQuestCreate) Save(ctx context.Context) (*UserQuest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserQuestCreate) SaveX(ctx context.Context) *UserQuest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserQuestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserQuestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserQuestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userquest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userquest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := userquest.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userquest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DateAt(); !ok {
		v := userquest.DefaultDateAt()
		_c.mutation.SetDateAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userquest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserQuestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserQuest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserQuest.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserQuest.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userquest.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserQuest.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuestID(); !ok {
		return &ValidationError{Name: "quest_id", err: errors.New(`ent: missing required field "UserQuest.quest_id"`)}
	}
	if v, ok := _c.mutation.QuestID(); ok {
		if err := userquest.QuestIDValidator(v); err != nil {
			return &ValidationError{Name: "quest_id", err: fmt.Errorf(`ent: validator failed for field "UserQuest.quest_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "UserQuest.progress"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserQuest.status"`)}
	}
	if _, ok := _c.mutation.DateAt(); !ok {
		return &ValidationError{Name: "date_at", err: errors.New(`ent: missing required field "UserQuest.date_at"`)}
	}
	return nil
}

func (_c *UserQuestCreate) sqlSave(ctx context.Context) (*UserQuest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserQuest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserQuestCreate) createSpec() (*UserQuest, *sqlgraph.CreateSpec) {
	var (
		_node = &UserQuest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userquest.Table, sqlgraph.NewFieldSpec(userquest.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userquest.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userquest.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userquest.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.QuestID(); ok {
		_spec.SetField(userquest.FieldQuestID, field.TypeString, value)
		_node.QuestID = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(userquest.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userquest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DateAt(); ok {
		_spec.SetField(userquest.FieldDateAt, field.TypeInt64, value)
		_node.DateAt = value
	}
	return _node, _spec
}

// UserQuestCreateBulk is the builder for creating many UserQuest entities in bulk.
type UserQuestCreateBulk struct {
	config
	err      error
	builders []*UserQuestCreate
}

// Save creates the UserQuest entities in the database.
func (_c *UserQuestCreateBulk) Save(ctx context.Context) ([]*UserQuest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserQuest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserQuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserQuestCreateBulk) SaveX(ctx context.Context) []*UserQuest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserQuestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserQuestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
