// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"isolo-news/internal/ent/predicate"
	"isolo-news/internal/ent/userquest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserQuestDelete is the builder for deleting a UserQuest entity.
type UserQuestDelete struct {
	config
	hooks    []Hook
	mutation *UserQuestMutation
}

// Where appends a list predicates to the UserQuestDelete builder.
func (_d *UserQuestDelete) Where(ps ...predicate.UserQuest) *UserQuestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserQuestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserQuestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserQuestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userquest.Table, sqlgraph.NewFieldSpec(userquest.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserQuestDeleteOne is the builder for deleting a single UserQuest entity.
type UserQuestDeleteOne struct {
	_d *UserQuestDelete
}

// Where appends a list predicates to the UserQuestDelete builder.
func (_d *UserQuestDeleteOne) Where(ps ...predicate.UserQuest) *UserQuestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserQuestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userquest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserQuestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
