// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/predicate"
	"isolo-news/internal/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v int64) *UserUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *UserUpdate) AddUpdatedAt(v int64) *UserUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetPlayerName sets the "player_name" field.
func (_u *UserUpdate) SetPlayerName(v string) *UserUpdate {
	_u.mutation.SetPlayerName(v)
	return _u
}

// SetNillablePlayerName sets the "player_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePlayerName(v *string) *UserUpdate {
	if v != nil {
		_u.SetPlayerName(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *UserUpdate) SetLevel(v int) *UserUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLevel(v *int) *UserUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *UserUpdate) AddLevel(v int) *UserUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetXp sets the "xp" field.
func (_u *UserUpdate) SetXp(v int) *UserUpdate {
	_u.mutation.ResetXp()
	_u.mutation.SetXp(v)
	return _u
}

// SetNillableXp sets the "xp" field if the given value is not nil.
func (_u *UserUpdate) SetNillableXp(v *int) *UserUpdate {
	if v != nil {
		_u.SetXp(*v)
	}
	return _u
}

// AddXp adds value to the "xp" field.
func (_u *UserUpdate) AddXp(v int) *UserUpdate {
	_u.mutation.AddXp(v)
	return _u
}

// SetMaxXp sets the "max_xp" field.
func (_u *UserUpdate) SetMaxXp(v int) *UserUpdate {
	_u.mutation.ResetMaxXp()
	_u.mutation.SetMaxXp(v)
	return _u
}

// SetNillableMaxXp sets the "max_xp" field if the given value is not nil.
func (_u *UserUpdate) SetNillableMaxXp(v *int) *UserUpdate {
	if v != nil {
		_u.SetMaxXp(*v)
	}
	return _u
}

// AddMaxXp adds value to the "max_xp" field.
func (_u *UserUpdate) AddMaxXp(v int) *UserUpdate {
	_u.mutation.AddMaxXp(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *UserUpdate) SetTitle(v string) *UserUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTitle(v *string) *UserUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *UserUpdate) ClearTitle() *UserUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdate) SetTags(v []string) *UserUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdate) AppendTags(v []string) *UserUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdate) ClearTags() *UserUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetReadArticleCount sets the "read_article_count" field.
func (_u *UserUpdate) SetReadArticleCount(v int) *UserUpdate {
	_u.mutation.ResetReadArticleCount()
	_u.mutation.SetReadArticleCount(v)
	return _u
}

// SetNillableReadArticleCount sets the "read_article_count" field if the given value is not nil.
func (_u *UserUpdate) SetNillableReadArticleCount(v *int) *UserUpdate {
	if v != nil {
		_u.SetReadArticleCount(*v)
	}
	return _u
}

// AddReadArticleCount adds value to the "read_article_count" field.
func (_u *UserUpdate) AddReadArticleCount(v int) *UserUpdate {
	_u.mutation.AddReadArticleCount(v)
	return _u
}

// SetLoginDays sets the "login_days" field.
func (_u *UserUpdate) SetLoginDays(v int) *UserUpdate {
	_u.mutation.ResetLoginDays()
	_u.mutation.SetLoginDays(v)
	return _u
}

// SetNillableLoginDays sets the "login_days" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLoginDays(v *int) *UserUpdate {
	if v != nil {
		_u.SetLoginDays(*v)
	}
	return _u
}

// AddLoginDays adds value to the "login_days" field.
func (_u *UserUpdate) AddLoginDays(v int) *UserUpdate {
	_u.mutation.AddLoginDays(v)
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetThemePreference sets the "theme_preference" field.
func (_u *UserUpdate) SetThemePreference(v string) *UserUpdate {
	_u.mutation.SetThemePreference(v)
	return _u
}

// SetNillableThemePreference sets the "theme_preference" field if the given value is not nil.
func (_u *UserUpdate) SetNillableThemePreference(v *string) *UserUpdate {
	if v != nil {
		_u.SetThemePreference(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserUpdate) SetEmailVerified(v bool) *UserUpdate {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmailVerified(v *bool) *UserUpdate {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v int64) *UserUpdate {
	_u.mutation.ResetLastLoginAt()
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *int64) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// AddLastLoginAt adds value to the "last_login_at" field.
func (_u *UserUpdate) AddLastLoginAt(v int64) *UserUpdate {
	_u.mutation.AddLastLoginAt(v)
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdate) ClearLastLoginAt() *UserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayerName(); ok {
		if err := user.PlayerNameValidator(v); err != nil {
			return &ValidationError{Name: "player_name", err: fmt.Errorf(`ent: validator failed for field "User.player_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := user.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "User.avatar_url": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(user.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerName(); ok {
		_spec.SetField(user.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(user.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(user.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Xp(); ok {
		_spec.SetField(user.FieldXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXp(); ok {
		_spec.AddField(user.FieldXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxXp(); ok {
		_spec.SetField(user.FieldMaxXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxXp(); ok {
		_spec.AddField(user.FieldMaxXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(user.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(user.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(user.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReadArticleCount(); ok {
		_spec.SetField(user.FieldReadArticleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadArticleCount(); ok {
		_spec.AddField(user.FieldReadArticleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginDays(); ok {
		_spec.SetField(user.FieldLoginDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginDays(); ok {
		_spec.AddField(user.FieldLoginDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.ThemePreference(); ok {
		_spec.SetField(user.FieldThemePreference, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(user.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastLoginAt(); ok {
		_spec.AddField(user.FieldLastLoginAt, field.TypeInt64, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v int64) *UserUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *UserUpdateOne) AddUpdatedAt(v int64) *UserUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetPlayerName sets the "player_name" field.
func (_u *UserUpdateOne) SetPlayerName(v string) *UserUpdateOne {
	_u.mutation.SetPlayerName(v)
	return _u
}

// SetNillablePlayerName sets the "player_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePlayerName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPlayerName(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *UserUpdateOne) SetLevel(v int) *UserUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLevel(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *UserUpdateOne) AddLevel(v int) *UserUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetXp sets the "xp" field.
func (_u *UserUpdateOne) SetXp(v int) *UserUpdateOne {
	_u.mutation.ResetXp()
	_u.mutation.SetXp(v)
	return _u
}

// SetNillableXp sets the "xp" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableXp(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetXp(*v)
	}
	return _u
}

// AddXp adds value to the "xp" field.
func (_u *UserUpdateOne) AddXp(v int) *UserUpdateOne {
	_u.mutation.AddXp(v)
	return _u
}

// SetMaxXp sets the "max_xp" field.
func (_u *UserUpdateOne) SetMaxXp(v int) *UserUpdateOne {
	_u.mutation.ResetMaxXp()
	_u.mutation.SetMaxXp(v)
	return _u
}

// SetNillableMaxXp sets the "max_xp" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableMaxXp(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetMaxXp(*v)
	}
	return _u
}

// AddMaxXp adds value to the "max_xp" field.
func (_u *UserUpdateOne) AddMaxXp(v int) *UserUpdateOne {
	_u.mutation.AddMaxXp(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *UserUpdateOne) SetTitle(v string) *UserUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTitle(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *UserUpdateOne) ClearTitle() *UserUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdateOne) SetTags(v []string) *UserUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdateOne) AppendTags(v []string) *UserUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdateOne) ClearTags() *UserUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetReadArticleCount sets the "read_article_count" field.
func (_u *UserUpdateOne) SetReadArticleCount(v int) *UserUpdateOne {
	_u.mutation.ResetReadArticleCount()
	_u.mutation.SetReadArticleCount(v)
	return _u
}

// SetNillableReadArticleCount sets the "read_article_count" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReadArticleCount(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetReadArticleCount(*v)
	}
	return _u
}

// AddReadArticleCount adds value to the "read_article_count" field.
func (_u *UserUpdateOne) AddReadArticleCount(v int) *UserUpdateOne {
	_u.mutation.AddReadArticleCount(v)
	return _u
}

// SetLoginDays sets the "login_days" field.
func (_u *UserUpdateOne) SetLoginDays(v int) *UserUpdateOne {
	_u.mutation.ResetLoginDays()
	_u.mutation.SetLoginDays(v)
	return _u
}

// SetNillableLoginDays sets the "login_days" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLoginDays(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetLoginDays(*v)
	}
	return _u
}

// AddLoginDays adds value to the "login_days" field.
func (_u *UserUpdateOne) AddLoginDays(v int) *UserUpdateOne {
	_u.mutation.AddLoginDays(v)
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetThemePreference sets the "theme_preference" field.
func (_u *UserUpdateOne) SetThemePreference(v string) *UserUpdateOne {
	_u.mutation.SetThemePreference(v)
	return _u
}

// SetNillableThemePreference sets the "theme_preference" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableThemePreference(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetThemePreference(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserUpdateOne) SetEmailVerified(v bool) *UserUpdateOne {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmailVerified(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v int64) *UserUpdateOne {
	_u.mutation.ResetLastLoginAt()
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// AddLastLoginAt adds value to the "last_login_at" field.
func (_u *UserUpdateOne) AddLastLoginAt(v int64) *UserUpdateOne {
	_u.mutation.AddLastLoginAt(v)
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdateOne) ClearLastLoginAt() *UserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayerName(); ok {
		if err := user.PlayerNameValidator(v); err != nil {
			return &ValidationError{Name: "player_name", err: fmt.Errorf(`ent: validator failed for field "User.player_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := user.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "User.avatar_url": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(user.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerName(); ok {
		_spec.SetField(user.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(user.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(user.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Xp(); ok {
		_spec.SetField(user.FieldXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXp(); ok {
		_spec.AddField(user.FieldXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxXp(); ok {
		_spec.SetField(user.FieldMaxXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxXp(); ok {
		_spec.AddField(user.FieldMaxXp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(user.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(user.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(user.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReadArticleCount(); ok {
		_spec.SetField(user.FieldReadArticleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadArticleCount(); ok {
		_spec.AddField(user.FieldReadArticleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginDays(); ok {
		_spec.SetField(user.FieldLoginDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginDays(); ok {
		_spec.AddField(user.FieldLoginDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.ThemePreference(); ok {
		_spec.SetField(user.FieldThemePreference, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(user.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastLoginAt(); ok {
		_spec.AddField(user.FieldLastLoginAt, field.TypeInt64, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeInt64)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
