// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"isolo-news/internal/ent/userachievement"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAchievementCreate is the builder for creating a UserAchievement entity.
type UserAchievementCreate struct {
	config
	mutation *UserAchievementMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAchievementCreate) SetCreatedAt(v int64) *UserAchievementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAchievementCreate) SetNillableCreatedAt(v *int64) *UserAchievementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAchievementCreate) SetUpdatedAt(v int64) *UserAchievementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAchievementCreate) SetNillableUpdatedAt(v *int64) *UserAchievementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserAchievementCreate) SetUserID(v string) *UserAchievementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAchievementID sets the "achievement_id" field.
func (_c *UserAchievementCreate) SetAchievementID(v string) *UserAchievementCreate {
	_c.mutation.SetAchievementID(v)
	return _c
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_c *UserAchievementCreate) SetUnlockedAt(v int64) *UserAchievementCreate {
	_c.mutation.SetUnlockedAt(v)
	return _c
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_c *UserAchievementCreate) SetNillableUnlockedAt(v *int64) *UserAchievementCreate {
	if v != nil {
		_c.SetUnlockedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserAchievementCreate) SetID(v string) *UserAchievementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserAchievementCreate) SetNillableID(v *string) *UserAchievementCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UserAchievementMutation object of the builder.
func (_c *UserAchievementCreate) Mutation() *UserAchievementMutation {
	return _c.mutation
}

// Save creates the UserAchievement in the database.
func (_c *UserAchievementCreate) Save(ctx context.Context) (*UserAchievement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAchievementCreate) SaveX(ctx context.Context) *UserAchievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAchievementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAchievementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAchievementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userachievement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userachievement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UnlockedAt(); !ok {
		v := userachievement.DefaultUnlockedAt()
		_c.mutation.SetUnlockedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userachievement.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAchievementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAchievement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAchievement.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAchievement.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userachievement.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserAchievement.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AchievementID(); !ok {
		return &ValidationError{Name: "achievement_id", err: errors.New(`ent: missing required field "UserAchievement.achievement_id"`)}
	}
	if v, ok := _c.mutation.AchievementID(); ok {
		if err := userachievement.AchievementIDValidator(v); err != nil {
			return &ValidationError{Name: "achievement_id", err: fmt.Errorf(`ent: validator failed for field "UserAchievement.achievement_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnlockedAt(); !ok {
		return &ValidationError{Name: "unlocked_at", err: errors.New(`ent: missing required field "UserAchievement.unlocked_at"`)}
	}
	return nil
}

func (_c *UserAchievementCreate) sqlSave(ctx context.Context) (*UserAchievement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserAchievement.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAchievementCreate) createSpec() (*UserAchievement, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAchievement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userachievement.Table, sqlgraph.NewFieldSpec(userachievement.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userachievement.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userachievement.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userachievement.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AchievementID(); ok {
		_spec.SetField(userachievement.FieldAchievementID, field.TypeString, value)
		_node.AchievementID = value
	}
	if value, ok := _c.mutation.UnlockedAt(); ok {
		_spec.SetField(userachievement.FieldUnlockedAt, field.TypeInt64, value)
		_node.UnlockedAt = value
	}
	return _node, _spec
}

// UserAchievementCreateBulk is the builder for creating many UserAchievement entities in bulk.
type UserAchievementCreateBulk struct {
	config
	err      error
	builders []*UserAchievementCreate
}

// Save creates the UserAchievement entities in the database.
func (_c *UserAchievementCreateBulk) Save(ctx context.Context) ([]*UserAchievement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAchievement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAchievementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAchievementCreateBulk) SaveX(ctx context.Context) []*UserAchievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAchievementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAchievementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
