// Code generated by ent, DO NOT EDIT.

package schedulesetting

import (
	"isolo-news/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCategoryID, v))
}

// CronExpression applies equality check predicate on the "cron_expression" field. It's identical to CronExpressionEQ.
func CronExpression(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCronExpression, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLTE(FieldCategoryID, v))
}

// CategoryIDContains applies the Contains predicate on the "category_id" field.
func CategoryIDContains(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldContains(FieldCategoryID, v))
}

// CategoryIDHasPrefix applies the HasPrefix predicate on the "category_id" field.
func CategoryIDHasPrefix(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldHasPrefix(FieldCategoryID, v))
}

// CategoryIDHasSuffix applies the HasSuffix predicate on the "category_id" field.
func CategoryIDHasSuffix(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldHasSuffix(FieldCategoryID, v))
}

// CategoryIDEqualFold applies the EqualFold predicate on the "category_id" field.
func CategoryIDEqualFold(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEqualFold(FieldCategoryID, v))
}

// CategoryIDContainsFold applies the ContainsFold predicate on the "category_id" field.
func CategoryIDContainsFold(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldContainsFold(FieldCategoryID, v))
}

// CronExpressionEQ applies the EQ predicate on the "cron_expression" field.
func CronExpressionEQ(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldCronExpression, v))
}

// CronExpressionNEQ applies the NEQ predicate on the "cron_expression" field.
func CronExpressionNEQ(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldCronExpression, v))
}

// CronExpressionIn applies the In predicate on the "cron_expression" field.
func CronExpressionIn(vs ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldIn(FieldCronExpression, vs...))
}

// CronExpressionNotIn applies the NotIn predicate on the "cron_expression" field.
func CronExpressionNotIn(vs ...string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNotIn(FieldCronExpression, vs...))
}

// CronExpressionGT applies the GT predicate on the "cron_expression" field.
func CronExpressionGT(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGT(FieldCronExpression, v))
}

// CronExpressionGTE applies the GTE predicate on the "cron_expression" field.
func CronExpressionGTE(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldGTE(FieldCronExpression, v))
}

// CronExpressionLT applies the LT predicate on the "cron_expression" field.
func CronExpressionLT(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLT(FieldCronExpression, v))
}

// CronExpressionLTE applies the LTE predicate on the "cron_expression" field.
func CronExpressionLTE(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldLTE(FieldCronExpression, v))
}

// CronExpressionContains applies the Contains predicate on the "cron_expression" field.
func CronExpressionContains(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldContains(FieldCronExpression, v))
}

// CronExpressionHasPrefix applies the HasPrefix predicate on the "cron_expression" field.
func CronExpressionHasPrefix(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldHasPrefix(FieldCronExpression, v))
}

// CronExpressionHasSuffix applies the HasSuffix predicate on the "cron_expression" field.
func CronExpressionHasSuffix(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldHasSuffix(FieldCronExpression, v))
}

// CronExpressionEqualFold applies the EqualFold predicate on the "cron_expression" field.
func CronExpressionEqualFold(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEqualFold(FieldCronExpression, v))
}

// CronExpressionContainsFold applies the ContainsFold predicate on the "cron_expression" field.
func CronExpressionContainsFold(v string) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldContainsFold(FieldCronExpression, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.FieldNEQ(FieldIsActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScheduleSetting) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScheduleSetting) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScheduleSetting) predicate.ScheduleSetting {
	return predicate.ScheduleSetting(sql.NotPredicates(p))
}
