# isolo-news 后端服务配置
server:
  port: 8080
  mode: debug          # debug / release / test
  read_timeout: 10s
  write_timeout: 10s

database:
  driver: postgres
  host: 39.101.75.31
  port: 5432
  user: postgres
  password: 1076236bb..
  dbname: isolo_news
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m

auth:
  jwt_secret: "isolonews_core_secret"
  access_token_ttl: 7200      # 2 小时（秒）
  refresh_token_ttl: 2592000  # 30 天（秒）
  email_verify_code_ttl: 600  # 10 分钟（秒）

smtp:
  host: "smtp.qq.com"
  port: 587
  username: "jsonkeys@foxmail.com"
  password: "ziihfwfftgnwbhge"
  from: "jsonkeys@foxmail.com"

casbin:
  model_path: "pkg/casbin/model.conf"
  policy_path: "pkg/casbin/policy.csv"

collector:
  timeout: 15           # HTTP 请求超时（秒）
  user_agent: "Mozilla/5.0 (compatible; IsoloNewsBot/1.0)"
  max_retries: 3
  retry_delay: 5        # 重试间隔（秒）

redis:
  host: "127.0.0.1"
  port: 6379
  password: "6379"
  db: 0
