// Code generated by ent, DO NOT EDIT.

package userachievement

import (
	"isolo-news/server/internal/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUserID, v))
}

// AchievementID applies equality check predicate on the "achievement_id" field. It's identical to AchievementIDEQ.
func AchievementID(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldAchievementID, v))
}

// UnlockedAt applies equality check predicate on the "unlocked_at" field. It's identical to UnlockedAtEQ.
func UnlockedAt(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUnlockedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldContainsFold(FieldUserID, v))
}

// AchievementIDEQ applies the EQ predicate on the "achievement_id" field.
func AchievementIDEQ(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldAchievementID, v))
}

// AchievementIDNEQ applies the NEQ predicate on the "achievement_id" field.
func AchievementIDNEQ(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldAchievementID, v))
}

// AchievementIDIn applies the In predicate on the "achievement_id" field.
func AchievementIDIn(vs ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldAchievementID, vs...))
}

// AchievementIDNotIn applies the NotIn predicate on the "achievement_id" field.
func AchievementIDNotIn(vs ...string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldAchievementID, vs...))
}

// AchievementIDGT applies the GT predicate on the "achievement_id" field.
func AchievementIDGT(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldAchievementID, v))
}

// AchievementIDGTE applies the GTE predicate on the "achievement_id" field.
func AchievementIDGTE(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldAchievementID, v))
}

// AchievementIDLT applies the LT predicate on the "achievement_id" field.
func AchievementIDLT(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldAchievementID, v))
}

// AchievementIDLTE applies the LTE predicate on the "achievement_id" field.
func AchievementIDLTE(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldAchievementID, v))
}

// AchievementIDContains applies the Contains predicate on the "achievement_id" field.
func AchievementIDContains(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldContains(FieldAchievementID, v))
}

// AchievementIDHasPrefix applies the HasPrefix predicate on the "achievement_id" field.
func AchievementIDHasPrefix(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldHasPrefix(FieldAchievementID, v))
}

// AchievementIDHasSuffix applies the HasSuffix predicate on the "achievement_id" field.
func AchievementIDHasSuffix(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldHasSuffix(FieldAchievementID, v))
}

// AchievementIDEqualFold applies the EqualFold predicate on the "achievement_id" field.
func AchievementIDEqualFold(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEqualFold(FieldAchievementID, v))
}

// AchievementIDContainsFold applies the ContainsFold predicate on the "achievement_id" field.
func AchievementIDContainsFold(v string) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldContainsFold(FieldAchievementID, v))
}

// UnlockedAtEQ applies the EQ predicate on the "unlocked_at" field.
func UnlockedAtEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldEQ(FieldUnlockedAt, v))
}

// UnlockedAtNEQ applies the NEQ predicate on the "unlocked_at" field.
func UnlockedAtNEQ(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNEQ(FieldUnlockedAt, v))
}

// UnlockedAtIn applies the In predicate on the "unlocked_at" field.
func UnlockedAtIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldIn(FieldUnlockedAt, vs...))
}

// UnlockedAtNotIn applies the NotIn predicate on the "unlocked_at" field.
func UnlockedAtNotIn(vs ...int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldNotIn(FieldUnlockedAt, vs...))
}

// UnlockedAtGT applies the GT predicate on the "unlocked_at" field.
func UnlockedAtGT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGT(FieldUnlockedAt, v))
}

// UnlockedAtGTE applies the GTE predicate on the "unlocked_at" field.
func UnlockedAtGTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldGTE(FieldUnlockedAt, v))
}

// UnlockedAtLT applies the LT predicate on the "unlocked_at" field.
func UnlockedAtLT(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLT(FieldUnlockedAt, v))
}

// UnlockedAtLTE applies the LTE predicate on the "unlocked_at" field.
func UnlockedAtLTE(v int64) predicate.UserAchievement {
	return predicate.UserAchievement(sql.FieldLTE(FieldUnlockedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAchievement) predicate.UserAchievement {
	return predicate.UserAchievement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAchievement) predicate.UserAchievement {
	return predicate.UserAchievement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAchievement) predicate.UserAchievement {
	return predicate.UserAchievement(sql.NotPredicates(p))
}
